Algoritmo "circulo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/9/2022
Var
// Seção de Declarações das variáveis 
      r, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreval("Digite o raio r do circulo")
      leia(r)
      
      area <-pi*exp(r,2)
      escreva("O valor da area do circulo eh: ", area:4:3)
      
      

Fimalgoritmo